<div id="login" class="login_form" style="display: none;">
   <div class="inner_div">
  <h1>Login</h1>
  <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="scaffold-form">
        <span onclick="document.getElementById('login').style.display='none'" class="close" title="Close Modal">&times;</span>
        <?php echo $this->getBlockHtml('formkey'); ?>
        <!-- <div class="col2-set"> -->
            <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
            <!-- <div class="col-1 new-users">
                <div class="content">
                    <h2><?php echo $this->__('New Here?') ?></h2>
                    <p class="form-instructions"><?php echo $this->__('Registration is free and easy!') ?></p>
                    <ul class="benefits">
                        <li><?php echo $this->__('Faster checkout') ?></li>
                        <li><?php echo $this->__('Save multiple shipping addresses') ?></li>
                        <li><?php echo $this->__('View and track orders and more') ?></li>
                    </ul>
                </div>
                <div class="buttons-set">
                    <a title="<?php echo $this->quoteEscape($this->__('Create an Account')) ?>" class="button" href="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>"><span><span><?php echo $this->__('Create an Account') ?></span></span></a>
                </div>
            </div> -->
            <?php endif; ?>
            <?php // This column should be col-1 if the registration column is not displayed ?>
            <div class="<?php if ($this->helper('customer')->isRegistrationAllowed()): ?>col-2<?php else: ?>col-1<?php endif; ?> registered-users">
                <div class="content fieldset">
                    <ul class="form-list">
                        <li>
                         <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->quoteEscape($this->__('Password')) ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <li>
                            <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                        </li>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    </ul>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                </div>
                <div class="buttons-set">
                    <button type="submit" class="button" title="<?php echo $this->quoteEscape($this->__('Login')) ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                </div>
            </div>
        <!-- </div> -->
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
 <!--  <form>
    <input type="email" name=""><br>
    <input type="password" name=""><br>
    <div class="login-button"><input type="submit" class="button" name="" value="Log In"></div>
</form>   -->
</div>
</div>



<style type="text/css">
    .login_form{
    display: block; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 20%;
    right: 0%;
    top: 15%;
    width: 70%; /* Full width */
    overflow: auto; /* Enable scroll if needed */
    /*background-color: rgb(0,0,0);*/ /* Fallback color */
    background-color: silver; /* Black w/ opacity */
    padding-top: 40px;
    padding-bottom: 40px;
    padding-right: 10px;
    padding-left: 10px;
    
    }
    h1{
        text-align: center;
    }
    .login-button{
        text-align: center;
    }
    .input-box{
        text-align: center;
    }
    .close {
    position: absolute;
    right: 25px;
    top: 0;
    color: black;
    font-size: 35px;
    font-weight: bold;
}

.inner_div{
       
       margin: 0px 207px; 
    }

</style>

<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery("span.label_login").click(function(e){
            e.preventDefault();
            jQuery(".login_form").css("display", "block");
            jQuery(".Register_form").css("display", "none");
            
        });
    });

    var dataForm = new VarienForm('login-form', true);
</script>