<?php
$order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order->loadByIncrementId($orderId);
?>
<h2><?php echo $this->__('PayU Payment Gateway') ?></h2>
<p>It's a PayU page acting as a payment gateway interface! So don't worry you won't get charged :-)</p>
<form name="PayU" method="post" action="<?php echo Mage::helper('PayU')->getPaymentGatewayUrl(); ?>">
  <input type="hidden" name="orderId" value="<?php echo $orderId; ?>">
  <input type="submit" value="<?php echo $this->__('Make Payment') ?>" />
</form>